Add new Cython-based RGB to HCL conversion
pytroll/trollimage pull request #122
Opened 2023-01-30 03:16 UTC by djhoese

This is a replacement for #121 that adds a cython extension to trollimage. This does mean a lot more complexity to the building of trollimage, but opens up a lot of doors for more optimizations in the future.

I commented on #79 about the performance I was seeing from #121 and how it was worse. I'm happy to say that with this new version the say test that took 1.68s in the version in `main` now takes 479ms. I still have some optimizations though.

TODO:
 - [ ] Decide/determine if the failing tests are just different numbers and not necessarily wrong
 - [ ] Add wheel building and upload to CI
 - [ ] Implement rgb2hcl in Cython (currently only have hcl2grb)
 - [ ] Refactor, refactor, refactor

 - [x] Closes #121, closes #79  (remove if there is no corresponding issue, which should only be the case for minor changes)
 - [ ] Tests added (for all bug fixes or enhancements)
 - [ ] Tests passed (for all non-documentation changes)
 - [ ] Passes ``git diff origin/master **/*py | flake8 --diff`` (remove if you did not edit any Python files)
 - [ ] Fully documented (remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later)

2023-01-30 17:30 UTC, djhoese commented
For performance, this script:

```python
from trollimage.colormap import Colormap
import numpy as np
cmap = Colormap(values=list(range(4)), colors=[(1.0, 1.0, 0.0), (0.0, 1.0, 1.0), (1.0, 1.0, 1.0), (0.0, 0.0, 0.0)])
data = np.random.random((3000, 3000))
colorized_image = cmap.colorize(data)
```

I run:

```bash
kernprof -l  profile_colorize.py
python -m line_profiler profile_colorize.py.lprof
```

And get:

```
Timer unit: 1e-06 s

Total time: 0.428572 s
File: /home/davidh/repos/git/trollimage/trollimage/colormap.py
Function: _interpolate_rgb_colors at line 92

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    92                                           @profile
    93                                           def _interpolate_rgb_colors(arr, colors, values):
    94         1          8.4      8.4      0.0      interp_xp_coords = np.array(values)
    95         1         35.8     35.8      0.0      interp_y_coords = rgb2hcl(colors)
    96         1          2.6      2.6      0.0      if values[0] > values[-1]:
    97                                                   # monotonically decreasing
    98                                                   interp_xp_coords = interp_xp_coords[::-1]
    99                                                   interp_y_coords = interp_y_coords[::-1]
   100                                               # handling NaN Hue values for interpolation
   101         1          0.7      0.7      0.0      new_hues = interp_y_coords[..., 0]
   102         1         35.5     35.5      0.0      if np.isnan(new_hues).all():
   103                                                   new_hues[..., :] = 0
   104                                               else:
   105         1          1.7      1.7      0.0          if np.isnan(new_hues[..., 0]):
   106                                                       new_hues[..., 0] = new_hues[~np.isnan(new_hues)][0]
   107         1          6.8      6.8      0.0          while np.isnan(new_hues).any():
   108                                                       new_hues[..., 1:] = np.where(np.isnan(new_hues[..., 1:]), new_hues[..., :-1], new_hues[..., 1:])
   109         1          1.4      1.4      0.0      interp_y_coords[..., 0] = new_hues
   110         1         12.4     12.4      0.0      interp_hcl = np.zeros(arr.shape + (3,), dtype=interp_y_coords.dtype)
   111         1     111445.3 111445.3     26.0      interp_hcl[..., 0] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 0])
   112         1      54063.3  54063.3     12.6      interp_hcl[..., 1] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 1])
   113         1      51841.0  51841.0     12.1      interp_hcl[..., 2] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 2])
   114         1     211114.2 211114.2     49.3      new_rgb = hcl2rgb(interp_hcl)
   115         1          2.9      2.9      0.0      return [new_rgb[..., 0], new_rgb[..., 1], new_rgb[..., 2]]

```

So hcl2rgb is still the slowest individual call.

2023-02-11 20:28 UTC, djhoese commented
So I started analyzing the failures of `test_colorize_with_interpolation` and tried to figure out which algorithm is more "right". So one of the results the test is supposed to product is 50%/50% between the first two colors of the colormap which are RGB (1.0, 1.0, 0.0) and (0.0, 1.0, 1.0). So yellow and cyan.

Here's what I get when I convert them to HCL:

```python
In [3]: rgb2hcl_old(1.0, 1.0, 0.0)
Out[3]: (80.17623543714927, 0.00501416179526073, -0.14337082984424737)

In [4]: rgb2hcl_old(0.0, 1.0, 1.0)
Out[4]: (169.421806448465, 0.0034564219537122592, -0.1440018813512837)

In [5]: rgb2hcl(np.array([[1.0, 1.0, 0.0]]))
Out[5]: array([[1.04719755, 0.66666667, 0.5       ]])

In [6]: rgb2hcl(np.array([[0.0, 1.0, 1.0]]))
Out[6]: array([[3.14159265, 0.66666667, 0.5       ]])
```

What I see here is that the new algorithm is much more consistent. For example, why is `C` in the old version different for two "full" colors on the HCL colorspace. Why is luminance negative? Here's the paper for this PR's algorithm if you want the full algorithm:

https://web.archive.org/web/20190220074017/http://pdfs.semanticscholar.org/206c/a4c4bb4a5b6c7b614b8a8f4461c0c6b87710.pdf

but here's the colorspace diagram:

![image](https://user-images.githubusercontent.com/1828519/218279775-cbcf0a0f-b174-4543-8771-42ce33d33c6a.png)

Let me see if I can generate the two versions of the colormaps as colorbars...

2023-02-11 20:34 UTC, djhoese commented
Old:

![colorbar_test_old](https://user-images.githubusercontent.com/1828519/218280013-ff50e4ca-930c-4cc8-8481-e0692d786cde.png)

New:

![colorbar_test_new](https://user-images.githubusercontent.com/1828519/218280015-63a49b69-ad5d-45be-91aa-7a1367a68e4e.png)

Hm that cyan to white in the new one definitely doesn't look right.

2023-02-11 21:50 UTC, djhoese commented
Newest commit fixes this:

![colorbar_test_new2](https://user-images.githubusercontent.com/1828519/218282580-2df114e8-402f-4809-ba28-396f229f6917.png)

2023-02-12 03:41 UTC, djhoese commented
I have another branch based on this one which completely reworks docs. I'd like to save that work for another PR.

2023-02-12 20:10 UTC, djhoese commented
So I had to update some other existing expected test results. The colormap used in that is brbg and I noticed a very small difference in the overall look.

Image with old colorize:

<img src="https://user-images.githubusercontent.com/1828519/218334323-826c074b-da85-4161-af5f-8cb699bf6852.png" width="150" height="50" style="image-rendering:pixelated;" alt="colorize_la_rgb_old.png"></img>

Image with new colorize:

<img src="https://user-images.githubusercontent.com/1828519/218334347-c4807e55-71b9-4531-94ea-dd469ba95f90.png" width="150" height="50" alt="colorize_la_rgb_new.png"></img>


Ugh, github is not rendering these nicely.

2023-02-15 03:24 UTC, djhoese commented
From what I can tell lost coverage is due to no tests for colorspaces.py and now that the hcl functions from that module aren't being used there are no tests touching them.

2023-02-15 17:40 UTC, mraspaud requested changes
I'm not so happy about having to use cython here, could you provide some performance measurements to convince me about this ? ;)
Some comments online, also don't forget to regenerate all the colorbars for the documentation
(I guess that's why we implemented trollimage.colormap.colorbar in the first place :)

2023-02-15 17:40 UTC, mraspaud commented on .github/workflows/ci.yaml
> +          pytest --cov=trollimage trollimage/tests --cov-report=xml --cov-report=
why the extra cov report here?

2023-02-15 17:40 UTC, mraspaud commented on trollimage/colormap.py
> +#     hcl_colors[:, 0] = np.rad2deg(np.unwrap(np.deg2rad(np.array(hcl_colors)[:, 0])))
I gather the unwrapping is done somewhere else?

2023-02-15 17:40 UTC, mraspaud commented on trollimage/colormap.py
> +    # TODO: Is this still true?
Could we check these todos before merging this?

2023-02-15 17:43 UTC, mraspaud commented
Just to report here, on slack @djhoese mentioned this colorspace: https://www.hsluv.org/
I have made a quick test with rdbu and got the following results:
Using hcl for interpolation
![rdbu_hcl](https://user-images.githubusercontent.com/167802/219109984-22bbb65b-12a9-4d37-9467-b90ced88056a.png)
Using hsluv for interpolation
![rdbu_hsluv](https://user-images.githubusercontent.com/167802/219109990-66bd002c-549e-4585-a28b-79b13e564fcd.png)

2023-02-15 17:52 UTC, djhoese commented on .github/workflows/ci.yaml
> +          pytest --cov=trollimage trollimage/tests --cov-report=xml --cov-report=
This is needed for coveralls which uses the default report type (we do this in all other pytroll package CIs that use both). Codecov uses the XML format. If we want to drop one of these pytroll-wide I vote for dropping codecov.

2023-02-15 17:53 UTC, djhoese commented on trollimage/colormap.py
> +#     hcl_colors[:, 0] = np.rad2deg(np.unwrap(np.deg2rad(np.array(hcl_colors)[:, 0])))
Good catch. I should probably check this. I couldn't find a case where it didn't look right, but I wasn't testing for something specifically that would require this wrapping.

2023-02-15 17:53 UTC, djhoese commented on trollimage/colormap.py
> +    # TODO: Is this still true?
Yes, I'll put the TODOs on my TODO list.

2023-02-15 18:03 UTC, mraspaud commented
Oh, wow, spectral is doing funky stuff with this PR :D
![spectral_pr](https://user-images.githubusercontent.com/167802/219114573-218972b3-189f-458e-a9f2-a243a8e7657b.png)

2023-02-15 18:03 UTC, djhoese commented
> I'm not so happy about having to use cython here, could you provide some performance measurements to convince me about this ? ;)

Are you kidding me? You could have said something one of the many times I brought up this concept up in slack and on this repository.

As for performance numbers, see this issue: https://github.com/pytroll/trollimage/issues/79. In my latest comment in that issue I point out how a colorize operation went from ~1.68s in main to <500ms in this branch. Additionally, in a comment above in this PR I have a line profiler that points out that even with this PR the slowest part of colorization is the hcl2rgb call.

Regarding the comparison with HSLuv, my original goal with this PR and the earlier pure-python version of the algorithm was to use the same colorspace that existed in main ("HCL") but with an algorithm that properly handles grayscale values. As mentioned in #106, any colormaps using black do not work well in `main`. Our results now that the algorithm is implemented in this PR do show some differences so the original HCL versus this HCL may not be the exact same colorspace. The lack of documentation for the existing colorspaces.py makes it hard to guess.

Your examples:

* Red/Blue: Yeah HSLuv definitely looks better.
* custom colormap: Oh wow, interesting. Yeah `main` looks much better. Maybe we just can't win.

2023-02-15 18:04 UTC, djhoese commented
That spectral result has to be related to wrapping the Hue angular values.

2023-02-15 18:11 UTC, mraspaud commented
> > I'm not so happy about having to use cython here, could you provide some performance measurements to convince me about this ? ;)
> 
> Are you kidding me? You could have said something one of the many times I brought this concept up in slack and on this repository.

I think I did mention it on slack, along with the comment that better performance wins, which this PR is clearly achieving, so no worries. I didn't mean to criticise your work here, sorry if it sounded like it. 

> As for performance numbers, see this issue: #79. In my latest comment in that issue I point out how a colorize operation went from ~1.68s in main to <500ms in this branch. Additionally, in a comment above in this PR I have a line profiler that points out that even with this PR the slowest part of colorization is the hcl2rgb call.

Thanks for the clarification.

> Regarding the comparison with HSLuv, my original goal with this PR and the earlier pure-python version of the algorithm was to use the same colorspace that existed in main ("HCL") but with an algorithm that properly handles grayscale values. As mentioned in #106, any colormaps using black do not work well in `main`. Our results now that the algorithm is implemented in this PR do show some differences so the original HCL versus this HCL may not be the exact same colorspace. The lack of documentation for the existing colorspaces.py makes it hard to guess.

Indeed, I can only blame myself for that lack of documentation, sorry.

> 
> Your examples:
> 
>     * Red/Blue: Yeah HSLuv definitely looks better.
> 
>     * custom colormap: Oh wow, interesting. Yeah `main` looks much better. Maybe we just can't win.

I think the hue unwrapping is the problem.

I edited the rdbu example above to add the rendering using this PR also.

2023-02-15 18:22 UTC, mraspaud commented on trollimage/colormap.py
> +    interp_y_coords[..., 0] = new_hues
```suggestion
    interp_y_coords[..., 0] = np.unwrap(new_hues)
```

2023-02-15 18:31 UTC, djhoese commented on trollimage/colormap.py
> +    interp_y_coords[..., 0] = new_hues
Do you have a screenshot of what spectral looks like with this?

2023-02-15 18:34 UTC, djhoese commented on trollimage/colormap.py
> +    interp_y_coords[..., 0] = new_hues
I think with this algorithm hue goes from -pi to pi, does that change how this call has to be done?

https://numpy.org/doc/stable/reference/generated/numpy.unwrap.html

2023-02-16 01:55 UTC, djhoese commented on trollimage/colormap.py
> +    # TODO: Is this still true?
These should all be completed now.

2023-02-16 02:00 UTC, djhoese commented
Did a quick test and the current version of this PR with all the new unwrap/ununwrap functions took ~593ms for the test I did in the related bottleneck issue. We could probably improve that a little bit by updating `hcl2rgb` to do things inplace. So a single input array that gets its elements overwritten. That would improve data locality and avoid having to allocate memory for another array of the same size. Thoughts?

I'd probably have to do the same to `rgb2hcl` for consistency, but maybe we don't want to do that. Oh I guess I could give it an inplace kwarg?

2023-02-16 02:05 UTC, djhoese commented
Nevermind, a quick test shows the inplace operation didn't make a difference. I'm not sure if I did something wrong or if I have to be smart about sending the same exactly array view in cython so it can optimize things. The C compiler also may not be smart enough to realize what I'm doing unless I create a separate inplace version of the nogil function.

2023-02-16 08:20 UTC, mraspaud commented on trollimage/_colorspaces.pyx
> +            not need to be changed from the default of 3.0.
I didn't check the paper (looks like it's paywalled), but does this relate to the usual gamma in which 1.0 is the default (no gamma applied)?

2023-02-16 08:22 UTC, mraspaud commented on trollimage/_colorspaces.pyx
> +            continue
Chroma equal to 0 also applies when luminance is 0 or 1, right?

2023-02-16 08:37 UTC, mraspaud commented on trollimage/colormap.py
> +    interp_hcl[..., 0] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 0])
I think I see what you are doing here to fill nans, taking the "left" neighbour, right?
But why not just use interpolation for this, eg:
```suggestion
        interp_xp_coords_hues = interp_xp_coords[~np.isnan(new_hues)]
        new_hues = new_hues[~np.isnan(new_hues)]  # only valid hues
    new_hues = np.unwrap(new_hues)
    interp_hcl = np.zeros(arr.shape + (3,), dtype=interp_y_coords.dtype)
    interp_hcl[..., 0] = np.interp(arr, interp_xp_coords_hues, new_hues, left=new_hues[..., 0], right=new_hues[..., -1])
```

2023-02-16 09:52 UTC, mraspaud commented on trollimage/colormap.py
> +    interp_hcl[..., 0] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 0])
Here is a comparison of the effect of this for rdbu.
This PR:
![rdbu_pr](https://user-images.githubusercontent.com/167802/219330886-37127512-567f-44d4-a0a3-a283b36c8651.png)
With the suggested change:
![rdbu_pr_mod](https://user-images.githubusercontent.com/167802/219330983-3caec02d-91cd-4ab2-b5a1-f42ec2e608f5.png)

2023-02-16 09:59 UTC, mraspaud commented on trollimage/colormap.py
> +    interp_hcl[..., 0] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 0])
Here is for the rdbu_simple I introduced in a previous example.
This PR:
![rdbu_simple_pr](https://user-images.githubusercontent.com/167802/219332243-1cb7ab15-ce1c-4a58-9bf3-149d4a1749b8.png)
With the suggested change:
![rdbu_simple_pr_mod](https://user-images.githubusercontent.com/167802/219332269-97f46eae-23f8-4023-9c6f-c36de3622dba.png)

Looks like the suggested change keeps better the perceptual gradients.

2023-02-16 10:44 UTC, mraspaud commented
Ok, I think I spotted a problem with this PR: the perceptual luminance gradient is not respected as well as it was in main.
Some examples, this PR on top, main on the bottom.
Spectral:
![spectral_pr_mod](https://user-images.githubusercontent.com/167802/219341575-38f94e62-60a7-4119-93c0-5cb1552b7470.png)
![spectral_main](https://user-images.githubusercontent.com/167802/219341598-3ea62a8e-319b-405d-a6df-5b7306313a3e.png)
I can see a clear luminance peak in the turquoise-green region.

Pubu:
![pubu_pr_mod](https://user-images.githubusercontent.com/167802/219342394-6acf9fe2-3c7c-45d2-baa0-c68315051336.png)
![pubu_main](https://user-images.githubusercontent.com/167802/219342428-60092d71-3a19-4349-a008-3234885af3d3.png)
I can see a darker purple peak at about the first third from the left, and a brighter blue peak in the middle.

I can also see some chroma deficiencies, eg in bupu:
![bupu_pr_mod](https://user-images.githubusercontent.com/167802/219343396-23f74fb5-5634-4591-90d4-33b8c31c092c.png)
![bupu_main](https://user-images.githubusercontent.com/167802/219343426-1224bca8-2221-48d0-bced-f9f37bc70caf.png)
Here it looks to me that the blue component disappeared altogether.

2023-02-16 12:53 UTC, djhoese commented
Can you paste the script you're using to generate these so we're doing the same comparisons? And are these last images with your changes to Hue NaN handling? And where were the values for these colormaps taken from? Matplotlib?

2023-02-16 13:09 UTC, mraspaud commented
Sure, here is the script, it generates colorbar images for all the sequential and diverging colormaps we have.

```python
from trollimage.image import Image
from trollimage.colormap import (colorbar,
                                 sequential_colormaps, diverging_colormaps)
sequential_colormaps_names = ["blues", "greens", "greys", "oranges", "purples", "reds",
                        "bugn", "bupu", "gnbu", "orrd", "pubu", "pubugn", "purd", "rdpu",
                        "ylgn", "ylgnbu", "ylorbr", "ylorrd"]
diverging_colormaps_names = ["brbg", "piyg", "prgn", "puor", "rdbu", "rdgy", "rdylbu", "rdylgn",
                       "spectral"]
for colormap, name in zip(sequential_colormaps + diverging_colormaps, sequential_colormaps_names + diverging_colormaps_names):
    cb = colorbar(400, 2000, colormap)
    channels = [cb[i, :, :] for i in range(3)]
    im =Image(channels=channels, mode="RGB")
    im.save(f"{name}_main.png")
```

> And are these last images with your changes to Hue NaN handling? 

Yes they are, but they look the same (in my eyes at least) to the ones with this PR only.

> And where were the values for these colormaps taken from? Matplotlib?

No, they are taken directly from colorbrewer2 if I remember correctly. (Which I think matplotlib does too, so it's probably the same)

2023-02-16 16:24 UTC, djhoese commented on trollimage/colormap.py
> +    interp_hcl[..., 0] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 0])
Oh I think there is a misunderstanding here. The NaN handling wasn't to remove the colors/elements with the NaNs in the Hue, that would remove entire colors from the colormap. It was meant to handle the case of grayscale colors where Hue results in NaN (done on purpose by me) and we need to take the previous hue. For example, if you had the color green which is a hue of like pi/3 and you needed to interpolate to the next color of white, the basic math of the algorithm could/would result in white having a hue of 0 (as a fallback for a `/ 0`). But we don't want hue to be interpolated between pi/3 and 0, we want hue to stay at pi/3 because when chroma is 0 hue has no effect.

The problem with my current approach though is that if we then interpolate from that white to blue (for example), we'd still be interpolating hue from pi/3 to pi instead of immediately jumping to pi. My guess/hope is that this happens for any grayscale color and that I can fix it. It may not help with the luminance/chroma issues you identified, but maybe it can clean up a couple other things.

Side note: I think your `left` and `right` keyword arguments match the default behavior of interp don't they?

2023-02-16 17:27 UTC, mraspaud commented on trollimage/colormap.py
> +    interp_hcl[..., 0] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 0])
Yes, I gathered that it was for handling monochromatic situations. But I hadn't understood that C and l were nans too then...

2023-02-16 17:30 UTC, djhoese commented on trollimage/colormap.py
> +    interp_hcl[..., 0] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 0])
I see now that you're only dropping the Nan elements in hue. One problem with this is it gets rid of the behavior of the control points. If the white hue was not perfectly between the two end colors then the hue interpolation between the two colors wouldn't be weighted properly. Like the middle color being at 0.4, we need to interpolate first to the 0.4 spot and then interpolate "more slowly" from 0.4 to 1.0...at least I think. Regardless, I don't think we want to interpolate hue in this case...right? Don't we want to go "straight" to the grayscale/monochromatic value and then from there (the center of the colorspace diagram) to the non-grayscale value.

2023-02-16 17:55 UTC, djhoese commented on trollimage/colormap.py
> +    interp_hcl[..., 0] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 0])
Ok I hacked a solution for the rdbu_simple example you did and here's what I get:

![rdbu_simple](https://user-images.githubusercontent.com/1828519/219447460-fff41160-b3e3-4821-9d1d-c490b0722e28.png)

Which to me looks as close to `main` as possible. I basically took the 3 HCL colors, repeated the 2 element (because it is NaN) and also repeated the `values` in the same way. Then I set the first NaN hue to hue[0] and the second NaN to hue[-1].

2023-02-16 17:56 UTC, djhoese commented on trollimage/colormap.py
> +    interp_hcl[..., 0] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 0])
Nevermind, that still looks very much like it did before but with better gradient on the blue side. The red side is still a different color I feel like.

2023-02-16 17:59 UTC, mraspaud commented on trollimage/colormap.py
> +    interp_hcl[..., 0] = np.interp(arr, interp_xp_coords, interp_y_coords[..., 0])
Regarding nans, doesn't this line show that only hues get nans? https://github.com/pytroll/trollimage/pull/122/files#diff-5f1ad72add694d03d94098c73ec8d5db5be7ef6ebb78648a606735d346769c0cR133
That would actually make sense, otherwise rdbu_simple wouldn't work at all: we need to keep the info that the middle point has 0 chroma and max luminance.

Regarding the interpolation technique:
Well, I think it depends on the situation. We can see artefacts in the diverging colormaps (also in main) because in principle we should have a discontinuity in the hue. Eg rdbu should be blue hue on the right and red on the left, and in the middle the hue has to change at exactly the middle point. Since we don't do that we get varying hues around the centre. (I intend to fix this in a future PR through the usage of `np.piecewise` or dask equivalent)

As for the usage of `interp`, you are absolutely right, the `right` and `left` parameters I proposed are redundant.

2023-02-16 20:22 UTC, djhoese commented
I'm going to summarize the conversation in some of the comments and on slack so that when we come back to this we aren't completely lost. Bottom line on this PR is:

1. Speed improvements :+1: 
2. This particular implementation of the HCL colorspace :-1: 

This stackoverflow answer points out that the paper is wrong (which I knew and used updated matlab code for it):

https://stackoverflow.com/a/11969277/9112384

But it also points out how terrible the actual algorithm is. @mraspaud thinks we should instead convert to CIE LCh_ab space which would require RGB -> XYZ -> Lab -> LCh_ab. @mraspaud does this sound right? How does this differ from the existing python-based version of the logic?

Martin also discovered that the original colorspace code is likely based on an old version of the chroma.js library (see https://github.com/gka/chroma.js/blob/97cc4223f4278aabc3fe99275305a759b1cbdaae/src/chroma.coffee#L411-L433 which is what appears in colorspaces.py, and http://www.vis4.net/blog/2011/12/avoid-equidistant-hsv-colors/, and the archived version of a deadlink there https://web.archive.org/web/20110926155739/http://davidad.net/colorviz/).

I think there are some good changes/updates in this PR that any changes should probably be based on this PR (to allow for cython usage) and include the updated docstrings, but the overall/new HCL conversions should be scrapped.

2023-02-16 20:33 UTC, mraspaud commented
> @mraspaud thinks we should instead convert to CIE LCh_ab space which would require RGB -> XYZ -> Lab -> LCh_ab. @mraspaud does this sound right? How does this differ from the existing python-based version of the logic?

Yes, that's right. The difference with the current implementation would be the last step lab -> hcl/Lch_ab, the latter being simpler.

> I think there are some good changes/updates in this PR that any changes should probably be based on this PR (to allow for cython usage) and include the updated docstrings, but the overall/new HCL conversions should be scrapped.

Agreed.

2023-02-24 16:56 UTC, djhoese commented
We mentioned it on slack but I don't think it got recorded here: we could probably borrow from some of the cython code here: https://github.com/mapbox/rio-color/blob/master/rio_color/colorspace.pyx#L96-L108

We'd likely want to change the code to be nogil and use memoryviews to be more dask friendly. I think I'd also like to avoid using the structs and enums they're using.

2023-08-03 02:04 UTC, djhoese commented
@mraspaud This PR needs a lot of cleanup, but the main functionality (new interpolation colormap interpolation code) is complete and seems to work pretty well. We'll have to generate some comparisons.

2023-08-03 02:09 UTC, djhoese commented
Main (top), PR (bottom):

![spectral_main_upstream](https://github.com/pytroll/trollimage/assets/1828519/e22b96e9-c619-4308-8a3a-177863a80837)

![spectral_main](https://github.com/pytroll/trollimage/assets/1828519/11fe8c74-6e1d-4918-9cb6-3131662803c5)

2023-08-11 12:27 UTC, mraspaud reviewed
That looks great, thanks for working on this! I have a couple of comments inline.

I see quite some code commented out. What do you plan to do with it?

Another thing I am worried about is the sRGB handling. As far as I know, the main branch is doing something wrong with sRGB (I think it's assuming the something is sRGB but isn't and thus converts mistakenly), so we should make sure we aren't doing the same here.

2023-08-11 12:27 UTC, mraspaud commented on trollimage/_colorspaces.pyx
> +    """Convert an HCL (hue, chroma, luminance) array to RGB.
```suggestion
    """Convert an LCH (hue, chroma, luminance) array to RGB.
```

2023-08-11 12:27 UTC, mraspaud commented on trollimage/_colorspaces.pyx
> +    """Convert numpy RGB[A] arrays to CIE LCh_ab (lch).
Should we add a ref to LCh_ab?

2023-08-11 12:27 UTC, mraspaud commented on trollimage/_colorspaces.pyx
> +cdef void _rgb_to_xyz(floating[:] red_arr, floating[:] green_arr, floating[:] blue_arr, floating[:, ::1] xyz_arr) nogil:
For this function and the following doing the conversion, I think it would be nice to have a link to the wikipedia page that give the coefficients used here.

2023-08-19 17:30 UTC, djhoese commented
@mraspaud here are the comparisons. Generated with:

```python
from trollimage.image import Image
from trollimage import colormap

branch = "main"
# branch = "hcl-cython"

for cmap_name, cmap_obj in colormap.__dict__.items():
    if not isinstance(cmap_obj, colormap.Colormap) or cmap_obj in colormap.qualitative_colormaps:
        continue

    cb = colormap.colorbar(400, 2000, cmap_obj)
    channels = [cb[i, :, :] for i in range(3)]
    print([ch[0, 0] for ch in channels])
    im = Image(channels=channels, mode="RGB")
    im.save(f"/home/davidh/repos/git/trollimage/colormaps_{branch}/{cmap_name}_{branch}.png")
```

In the below images, main is always on top, this PR always on bottom. I've only copied some of the ones where I noticed a difference:

### ylorrd

I would say the difference in this colormap is seen in most of the colormaps. Kind of an extension/shifting of the transition towards the colors on the end.

![ylorrd_main](https://github.com/pytroll/trollimage/assets/1828519/89536645-05d4-4659-8aed-b4bad6dee2c1)

![ylorrd_hcl-cython](https://github.com/pytroll/trollimage/assets/1828519/f4317e45-5d41-41a9-bd1b-b67d6280bf0d)

### ylgnbu

This is by far the worst one. Looking at the definition though it only has two colors instead of 3 like the name suggests.

```python
ylgnbu = Colormap((0.000, (1.0, 1.0, 217 / 255.0)),
                  (1.000, (8 / 255.0, 29 / 255.0, 88 / 255.0)))
```

![ylgnbu_main](https://github.com/pytroll/trollimage/assets/1828519/8f79cd79-277f-48e6-84d9-bec3bfb80357)

![ylgnbu_hcl-cython](https://github.com/pytroll/trollimage/assets/1828519/b46c9de9-ce16-4630-be62-66412680eb3e)

### rainbow

![rainbow_main](https://github.com/pytroll/trollimage/assets/1828519/964a6457-03d1-4d19-b626-1d4398cfc8cb)

![rainbow_hcl-cython](https://github.com/pytroll/trollimage/assets/1828519/4ff97e55-e46d-4024-9568-ade7b826ea85)

### rdgy

Note the appearance of the green near the center-left. Similar green-ish color shows up in `rdbu` and `puor` too. In `prgn` there is a "blue" color near the center but it switches from the right side of center in `main` to the left side in this PR.

![rdgy_main](https://github.com/pytroll/trollimage/assets/1828519/c6acd21a-a8da-408b-b4bd-8d44df660048)

![rdgy_hcl-cython](https://github.com/pytroll/trollimage/assets/1828519/d94fae55-2eac-469f-a4f0-7cdda83ed317)

### orrd

![orrd_main](https://github.com/pytroll/trollimage/assets/1828519/03f06c8e-3f73-46b4-be6c-57679efb3eab)

![orrd_hcl-cython](https://github.com/pytroll/trollimage/assets/1828519/5589bf19-1024-45bb-90bd-166e387a146e)

### greys

I think the blending is much better in this PR. Smoother transition.

![greys_main](https://github.com/pytroll/trollimage/assets/1828519/52eac8ab-a34d-4a65-a059-8049ebf34307)

![greys_hcl-cython](https://github.com/pytroll/trollimage/assets/1828519/baaded1d-8dce-4c33-99fe-cc0236a8862d)

2023-08-21 06:43 UTC, mraspaud commented
Re YlGnBu, we should definitely add more intermediate colors, maybe these: https://colorbrewer2.org/#type=sequential&scheme=YlGnBu&n=9

2023-08-21 13:22 UTC, djhoese commented on trollimage/_colorspaces.pyx
> +cdef void _rgb_to_xyz(floating[:] red_arr, floating[:] green_arr, floating[:] blue_arr, floating[:, ::1] xyz_arr) nogil:
A link to all the colorspace wikipedia articles was added in the public convert function. Not sure that is good enough, but it's at least documented in the module.

2023-08-22 07:36 UTC, mraspaud approved these changes
LGTM. Thanks for putting in all the effort, it's just a bit disappointing it didn't improve the performance that much.

2023-08-22 07:36 UTC, mraspaud commented
Tests are failing though...

2023-08-22 11:52 UTC, djhoese commented
I'll spend an hour or so today seeing if I flip the logic around if it changes performance: I'm thinking if I do the for loop on the outer convert function and then passing every pixel in to the sub-functions that it should improve performance based on memory locality. I think for simplicity of code I'm going to pass pixel colors by reference instead of by value. Or at least the output. That way all functions can remain `void` for returns and I don't have to worry about creating stuff on the stack...I think. Do you have other ideas @mraspaud? The `rio-color` project did a struct that it assigned to and then returned. I'm not sure I want to go down that road but I don't have a strong reason either.

2023-08-22 12:55 UTC, mraspaud commented
> I'll spend an hour or so today seeing if I flip the logic around if it changes performance: I'm thinking if I do the for loop on the outer convert function and then passing every pixel in to the sub-functions that it should improve performance based on memory locality. I think for simplicity of code I'm going to pass pixel colors by reference instead of by value. Or at least the output. That way all functions can remain `void` for returns and I don't have to worry about creating stuff on the stack...I think. Do you have other ideas @mraspaud? The `rio-color` project did a struct that it assigned to and then returned. I'm not sure I want to go down that road but I don't have a strong reason either.

I have to admit I can't think of much right now....
- I see in some places that delta * delta is used, maybe having a delta_square constant could help a bit.
- There are some primitives in cuda for color conversions if we want to go that way. https://docs.nvidia.com/cuda/npp/group__image__color__model__conversion.html
- Otherwise I suppose you compared to the scikit images implementations? https://scikit-image.org/docs/stable/api/skimage.color.html#skimage.color.rgb2xyz

One more thing I saw now when looking at the code again: could we extract methods for the rgb to and from srgb conversions? I think it would make the code a bit nicer.

2023-08-22 12:59 UTC, mraspaud commented
also opencv and corresponding python bindings could make things much faster if we want to test https://docs.opencv.org/3.4/de/d25/imgproc_color_conversions.html

2023-08-22 13:35 UTC, mraspaud commented
this https://github.com/pytroll/trollimage/pull/122/files#diff-5f1ad72add694d03d94098c73ec8d5db5be7ef6ebb78648a606735d346769c0cR441-R453 and this https://github.com/pytroll/trollimage/pull/122/files#diff-5f1ad72add694d03d94098c73ec8d5db5be7ef6ebb78648a606735d346769c0cR299-R311

2023-08-22 14:34 UTC, djhoese commented
Ah sure. I could make a little inline function for the individual component operation. I think I'll leave the simplified version as it is.

2023-08-22 18:29 UTC, djhoese commented
Oh and no I haven't looked at those other libraries/tools because I was trying to avoid another dependency for only a small portion of what this library does and for such a small portion of what those libraries does (lots of extra functionality we aren't using).

2023-08-23 06:23 UTC, mraspaud commented
> Oh and no I haven't looked at those other libraries/tools because I was trying to avoid another dependency for only a small portion of what this library does and for such a small portion of what those libraries does (lots of extra functionality we aren't using).

true.

2023-08-24 01:47 UTC, merged

2023-08-24 01:48 UTC, djhoese commented
As mentioned on slack, I will follow this PR up with an optimization PR and a PR to auto-generate the colormap images used in the docs.