Make sure no cast warning is issued when saving
pytroll/trollimage pull request #149
Opened 2023-10-24 09:53 UTC by mraspaud

This PR ensures no cast warning is raised when saving an image that contains nans to int. 

Includes a refactor of one big test method.

 - [x] Tests added (for all bug fixes or enhancements)
 - [x] Tests passed (for all non-documentation changes)
 - [x] Passes ``git diff origin/master **/*py | flake8 --diff`` (remove if you did not edit any Python files)

2023-10-24 19:16 UTC, djhoese requested changes
If it comes down to it, I'm OK merging this as is. However, I had one inline comment and if you have any time I'd like a review of methods like:

https://github.com/mraspaud/trollimage/blob/5a8519d4b6df9ab67b1f432e1d4b1d92fea351bc/trollimage/xrimage.py#L824-L837

And see if something in those should be updated to do this fillna there.

Otherwise, could we get something in the docstring (maybe the main `save` at least?) about the behavior of NaNs/NA handling? Normally I wouldn't mind for such a small change, but as mentioned on slack this is really defining a previously undefined behavior so it'd be nice to document it.

2023-10-24 19:16 UTC, djhoese commented on trollimage/xrimage.py
> +                data = data.fillna(np.iinfo(dtype).min)
Correct me if I'm wrong, but while looking for where this `_scale_to_dtype` method is used I noticed there is a spot where right after this method is called the `_replace_fill_value` method is called and I think when the second argument (`ifill`) is passed as `None` it performs the equivalent of what you've done here. We may want to reuse that method. However, you'd still have to do the `iinfo` so maybe this isn't worth it.

2023-12-09 02:40 UTC, djhoese commented
This PR just got more interesting to me. I have a local branch where I'm trying to remove all test warnings. I ran into the ones fixed here and remembered this PR existed. What were you thoughts on my comment(s)?

2023-12-11 15:44 UTC, mraspaud commented
> What were you thoughts on my comment(s)?

They make sense, but I didn't have the time to investigate further yet.

2023-12-16 19:54 UTC, djhoese commented
I spent a lot of time looking at this and how the scale method is called in different ways and I couldn't find a way to refactor this stuff without starting from scratch. At first I was able to reuse some of the logic, but ran into issues when this `fillna` that is being added is for integer output but to provide a fill value (the `np.iinfo(dtype).min`) means for floating point input data we scale it with the fill value in mind (ex. scale 1-255 but leave 0 for fill value only). This particular fillna addition is not meant to have an effect on the data output so it means I/we can't reuse the existing methods. So I left @mraspaud's code as-is.

I did make a change to how the test was working. When working out what was failing I got annoyed that the existing warning check was happening at the end of the test function rather than the actual `.save` call that was producing it. It now does it at the specific line.

2023-12-16 19:55 UTC, merged