Change XRImage.save to keep fill_value separate from valid data
pytroll/trollimage pull request #75
Opened 2020-11-09 19:41 UTC by djhoese

This PR is a big change in the sense that it changes the output of any XRImage save that passes a `fill_value`. The main problem I'm trying to avoid here is having a single output/image value that represents both invalid and valid data. Take for example this fake XRImage data that we would like to save:

```
[[0.5, 0.5, 0.5, 0.5, 0.5],
 [0.5, 0.5, 0.5, 0.5, 0.5],
 [0.0, 0.0, 0.0, 0.0, np.nan],
 [0.5, 0.5, 0.5, 0.5, 0.5],
 [0.5, 0.5, 0.5, 0.5, 0.5]]
```

In this data, `np.nan` is used to mark a pixel as invalid and is what xarray will do by default. Now with the current master branch version of trollimage if I did `my_xrimg.save("test.png", fill_value=0)`, my resulting image would contain:

```
[[128, 128, 128, 128, 128],
 [128, 128, 128, 128, 128],
 [128, 128, 128, 0, 0],
 [128, 128, 128, 128, 128],
 [128, 128, 128, 128, 128]]
```

With this PR you would get:

```
[[129, 129, 129, 129, 129],
 [129, 129, 129, 129, 129],
 [129, 129, 129, 1, 0],
 [129, 129, 129, 129, 129],
 [129, 129, 129, 129, 129]]
```

In the master branch version we can't tell the difference between valid and invalid data. In this PR's version there is an explicit offset so valid data will never equal the value used for invalid data.

Note:

1. This PR only does this for float data being saved to integers. Integer input data (think category data) is not changed.
2. This PR only does this behavior for a `fill_value` that is the minimum or maximum of the data type that is being saved to. So in the default uint8 case a fill_value of 0 and 255 will be unique fill values. Anything else produces a warning that the valid and invalid data overlap.

I technically documented this in the save docstring but feel it should probably be mentioned somewhere else, but I'm not sure where. Additionally this PR does **not** modify the regular numpy Image class.

I'm realizing that one major downside to this might be if someone specifically enhanced/stretched their data and then expected to undo that scaling on the resulting image data, they would get different results.

 - [x] Tests added (for all bug fixes or enhancements)
 - [x] Tests passed (for all non-documentation changes)
 - [ ] Passes ``git diff origin/master **/*py | flake8 --diff`` (remove if you did not edit any Python files)
 - [ ] Fully documented (remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later)

2020-11-11 08:12 UTC, pnuu commented
> one major downside to this might be if someone specifically enhanced/stretched their data and then expected to undo that scaling on the resulting image data

Indeed, this can cause a lot of confusion. Setting `fill_value=0` for integer data causes the remaining values to be scaled between 1 and 255. For categorical data this can lose valid data and merge different categories together, which is very undesirable.

2020-11-11 15:10 UTC, djhoese commented
> This PR only does this for float data being saved to integers. Integer input data (think category data) is not changed.

That's why integer data isn't touched. Only float (including previously enhanced data) is done this way.

2020-11-17 09:47 UTC, mraspaud requested changes
LGTM, I trust you (and the tests) on the maths. A couple of style comments.

2020-11-17 09:47 UTC, mraspaud commented on trollimage/xrimage.py
> +                            "being saved to.")
This should be a separate method.

2020-11-17 09:47 UTC, mraspaud commented on trollimage/xrimage.py
> +                If specified, it must be the minimum or maximum of the
```suggestion
                If specified, it should be the minimum or maximum of the
```

2020-11-17 09:47 UTC, mraspaud commented on trollimage/tests/test_image.py
> +        """Test saving to simple image formats."""
This method should become its own test case with multiple methods.

2020-11-17 13:48 UTC, djhoese commented on trollimage/xrimage.py
> +                If specified, it must be the minimum or maximum of the
Good catch. I wrote the docstring before writing the code and changed my mind about the behavior while writing the code.

2020-11-17 13:51 UTC, djhoese commented on trollimage/tests/test_image.py
> +        """Test saving to simple image formats."""
Damn. I knew you were going to say that. I thought so too but didn't want to tackle it here. I'll see how difficult it would be. It would be nice if I could use pytest parameterize again but the cases might be a little too complicated.

2020-11-17 13:52 UTC, mraspaud commented on trollimage/tests/test_image.py
> +        """Test saving to simple image formats."""
Am I so predictable? ;)

2020-11-17 13:55 UTC, djhoese commented on trollimage/tests/test_image.py
> +        """Test saving to simple image formats."""
Well wouldn't you know it, there are some duplicate tests in here. :man_facepalming:

2020-12-14 02:05 UTC, djhoese commented
@mraspaud If you have any other problems with this let me know, otherwise merging tomorrow.

2020-12-14 07:25 UTC, mraspaud reviewed
Just one suggestion, otherwise LGTM

2020-12-14 07:25 UTC, mraspaud commented on trollimage/xrimage.py
> +                result in data being scaled linearly from 1 to 255.
```suggestion
                result in floating-point data being scaled linearly from 1 to 255.
```

2020-12-14 15:36 UTC, merged