Fix Colormap not being able to merge RGB and RGBA colormaps
pytroll/trollimage pull request #81
Opened 2021-06-14 16:54 UTC by djhoese

- [x] Closes https://github.com/pytroll/satpy/issues/1658 (remove if there is no corresponding issue, which should only be the case for minor changes)
 - [x] Tests added (for all bug fixes or enhancements)
 - [x] Tests passed (for all non-documentation changes)

2021-06-14 19:25 UTC, mraspaud requested changes
A few comments.

2021-06-14 19:25 UTC, mraspaud commented on trollimage/colormap.py
> +            # empty colormap
What's the use of an empty colormap?

2021-06-14 19:25 UTC, mraspaud commented on trollimage/colormap.py
> +            elements as colors.
Monotonicity?

2021-06-14 19:25 UTC, mraspaud commented on trollimage/colormap.py
> +            raise ValueError("Colormap 'values' must be monotonically increasing.")
Won't this and the previous error be caught later on with the interpolation?

2021-06-14 19:25 UTC, mraspaud commented on trollimage/colormap.py
> +        return dict(zip(self.values, tuple(map(tuple, colors))))
Good catch! A test should be added to ensure that the colors are not modified.

2021-06-14 19:33 UTC, djhoese commented on trollimage/colormap.py
> +    def _normalize_color_arrays(self, cmap1, cmap2):
Yes.

2021-06-14 19:35 UTC, djhoese commented on trollimage/colormap.py
> +            return cmap1.to_rgba(), cmap2
Maybe, but right now I make sure that Colormaps are either RGB or RGBA so this should never actually be encountered unless someone modified their colormap in a way they shouldn't.

2021-06-14 19:36 UTC, djhoese commented on trollimage/colormap.py
> +            # empty colormap
Good question. No idea, but it is done a lot (or was) in the Colormap class itself and in the tests. I can remove the option to make an empty colormap if that'd be better.

2021-06-14 19:37 UTC, djhoese commented on trollimage/colormap.py
> +            # empty colormap
Just ran all the tests and it looks like it isn't used anymore except for the specific test I added for it. I removed all the uses for it in this PR.

2021-06-14 19:40 UTC, djhoese commented on trollimage/colormap.py
> +            raise ValueError("Colormap 'values' must be monotonically increasing.")
Tough call. Yes, maybe, but I don't know what the error will say (it will likely not make sense to a Colormap user) and that won't happen until someone actually colorizes (not sure what palettize does). This makes sure the error happens right away and gives a logical error for the Colormap user.

2021-06-14 19:42 UTC, djhoese commented on trollimage/colormap.py
> +        return dict(zip(self.values, tuple(map(tuple, colors))))
I updated the existing to_rio test to make sure it doesn't modify the values (hopefully this URL points to the right line):

https://github.com/pytroll/trollimage/pull/81/files#diff-aaf6ed6ebec52d1befbb4feec36e506e5c4cce426ff712d12caea328cb4c83b4R217

2021-06-14 19:55 UTC, mraspaud commented on trollimage/colormap.py
> +            return cmap1.to_rgba(), cmap2
Haha, no, I'm actually suggesting replacing the if/elif with an else.

2021-06-14 19:57 UTC, djhoese commented on trollimage/colormap.py
> +            return cmap1.to_rgba(), cmap2
Ah, only downside then is it is an extra copy of the values and colors as `to_rgba` produces a new instance with new arrays.

2021-06-14 19:57 UTC, djhoese commented on trollimage/colormap.py
> +            # empty colormap
Should I remove the test and the check? The rest of the `_validate_X` methods will fail if it is empty.

2021-06-14 19:59 UTC, mraspaud commented on trollimage/colormap.py
> +            raise ValueError("Colormap 'values' must be monotonically increasing.")
Hmm, OK. I don't really like having this checked twice, because it clutters the code and might slow things down for large colormaps (which in practice never happens, ok). But alright, I guess this is fine.

2021-06-14 19:59 UTC, mraspaud commented on trollimage/colormap.py
> +            return cmap1.to_rgba(), cmap2
Could you modify to_rgba to pass through if the size is right?

2021-06-14 20:00 UTC, mraspaud commented on trollimage/colormap.py
> +            # empty colormap
Yes

2021-06-14 20:01 UTC, djhoese commented on trollimage/colormap.py
> +            raise ValueError("Colormap 'values' must be monotonically increasing.")
Yeah I thought about that too and it is one of the reasons I don't do other checks during `__init__`. I can't imagine people having more than 256 elements in their colormap though (in most cases) so that's why I'm ok with this. Hhhhmmm, however, it does mean that there is now even more work to be done when trollimage is imported as it has to create all of its Colormap instances. :thinking:

2021-06-14 20:15 UTC, djhoese commented on trollimage/colormap.py
> +            return cmap1.to_rgba(), cmap2
Ok this is done, but I did something you might ask me to change anyway. I still check that at least one of the colormaps are RGBA before doing `to_rgba`. This is kind of future-proofing for if/when someone wants to add support for L and LA colormaps (something I specifically check for in `__init__` now).

If you feel strongly about it I'll remove it.

2021-06-15 06:41 UTC, mraspaud commented on trollimage/colormap.py
> +            return cmap1.to_rgba(), cmap2
looks good!

2021-06-15 12:12 UTC, mraspaud reviewed
Just a couple of small comments

2021-06-15 12:12 UTC, mraspaud commented on trollimage/colormap.py
> +        colors2 = cmap2.colors
these could be inlined

2021-06-15 16:17 UTC, djhoese commented on trollimage/colormap.py
> +            raise ValueError("Colormap 'values' must be monotonically increasing.")
I've moved this operation to only be on the `__add__` method for performance reasons.

2021-06-15 16:18 UTC, djhoese commented on trollimage/colormap.py
> +            raise ValueError("Colormap 'colors' should be floating point numbers between 0 and 1.")
I made this into a warning and now cast to float. I've decided to avoid any checks of the actually content/values of the arrays from `__init__` for performance reasons.

2021-07-03 20:42 UTC, djhoese commented
@mraspaud when you're back from vacation could you re-review this?

2021-07-13 15:30 UTC, mraspaud reviewed
Looks good so far. I just have one styling comment, and then the raises exceptions aren't tested according to codecov?

2021-07-13 15:30 UTC, mraspaud commented on trollimage/colormap.py
> +        colors[:, 3] = 1.0
how about:
```python
colors = np.append(self.colors, np.ones((self.colors.shape[0], 1), dtype=self.colors.dtype), axis=1)
```

2021-07-13 18:11 UTC, djhoese commented on trollimage/colormap.py
> +        colors[:, 3] = 1.0
That creates two arrays, my way creates one. :man_shrugging:

2021-07-14 06:22 UTC, mraspaud commented on trollimage/colormap.py
> +        colors[:, 3] = 1.0
how so? you mean with `np.ones`?

2021-07-14 15:17 UTC, mraspaud commented on trollimage/colormap.py
> +        colors[:, 3] = 1.0
Ok. I would argue that the array is small, but since my solution isn't clearer or nicer than yours, I'll just drop it :)

2021-07-14 18:37 UTC, djhoese commented
Ok tests have been added. There is an exception in `_normalize_color_arrays` that can't be tested without purposely passing something that looks like a Colormap object but isn't. That's because you can't create a Colormap that isn't RGB/RGBA so you can't trigger the case where you merge two colormaps that can't be normalized to RGB or RGBA.

2021-07-14 19:16 UTC, mraspaud commented
So do we need that error?

2021-07-14 19:21 UTC, djhoese commented
If someone in the future adds the ability for colormaps to be specified with L or LA colors, then this method has to be updated to support that and then there are no logical other options that would produce this error (L, LA, RGB, RGBA). :thinking: I guess I'll get rid of it.

2021-07-14 19:23 UTC, djhoese commented
Ok I've updated it and now it forces everything to RGBA. So even in the future this should work, but may not be the most efficient if someone wants to merge an L and LA colormap, but that can be an optimization that is added on later.

2021-07-15 06:17 UTC, mraspaud commented
Sounds great!

2021-07-15 06:19 UTC, mraspaud approved these changes
LGTM!

2021-07-15 06:19 UTC, merged